#!/usr/bin/env python3
"""Select the prebuilt filter bank entries from the raw sweep CSV and emit
SourceDetachedPole/PresetFilterBank.h.

Selection rule per (sampleRateHz, attenuationDb):
  1. Restrict to rows that are feasible AND sane (worstStopbandDb within
     [-110, -85] dB - the sweep targeted -95dB, so a real converged hit
     lands within a few tenths of that; anything wildly outside this
     window, including the exact-0.0 infeasible sentinel and the
     numerically-degenerate positive-dB readings seen at some larger M's,
     is discarded rather than risking it being picked as "best").
  2. M_best = the sane row with the lowest R_peak; R_min = its R_peak.
  3. Candidate set = sane rows with R_peak <= R_min * 1.20 (20% relative).
  4. fastest = the candidate with the shortest T_0.1% (settlingMs).
  5. Choose fastest over M_best only if fastest's settlingMs is more than
     40% relatively shorter than M_best's; otherwise keep M_best.
"""
import csv
import sys

SRC_CSV = "bank_sweep.csv"
OUT_HEADER = "PresetFilterBank.h"

SANE_STOPBAND_LO = -110.0
SANE_STOPBAND_HI = -85.0
R_PEAK_BAND_REL = 1.20
SETTLING_IMPROVEMENT_REL = 0.40

def load_rows(path):
    rows = []
    with open(path, newline="") as f:
        for r in csv.DictReader(f):
            r["sampleRateHz"] = float(r["sampleRateHz"])
            r["attenuationDb"] = float(r["attenuationDb"])
            r["M"] = int(r["M"])
            r["tapCount"] = int(r["tapCount"])
            r["feasible"] = r["feasible"] == "1"
            r["worstStopbandDb"] = float(r["worstStopbandDb"])
            r["rPeakPercent"] = float(r["rPeakPercent"])
            r["settlingSampleSpan"] = int(r["settlingSampleSpan"])
            r["settlingMs"] = float(r["settlingMs"])
            r["taps"] = [float(x) for x in r["taps"].split(";")] if r["taps"] else []
            rows.append(r)
    return rows

def is_sane(r):
    return r["feasible"] and SANE_STOPBAND_LO <= r["worstStopbandDb"] <= SANE_STOPBAND_HI

def select_pair(rows):
    sane = [r for r in rows if is_sane(r)]
    if not sane:
        return None, "no sane feasible row"
    m_best = min(sane, key=lambda r: r["rPeakPercent"])
    r_min = m_best["rPeakPercent"]
    band = r_min * R_PEAK_BAND_REL
    candidates = [r for r in sane if r["rPeakPercent"] <= band]
    fastest = min(candidates, key=lambda r: r["settlingMs"])
    chosen = m_best
    note = "kept M_best (lowest R_peak)"
    if fastest is not m_best and fastest["settlingMs"] < m_best["settlingMs"] * (1.0 - SETTLING_IMPROVEMENT_REL):
        chosen = fastest
        note = f"switched to faster-settling M={fastest['M']} (R_peak {fastest['rPeakPercent']:.3f}% vs best {r_min:.3f}%)"
    return chosen, note

def fmt_double(x):
    return repr(x)

def main():
    rows = load_rows(SRC_CSV)
    pairs = {}
    for r in rows:
        key = (r["sampleRateHz"], r["attenuationDb"])
        pairs.setdefault(key, []).append(r)

    entries = []
    for key in sorted(pairs.keys()):
        chosen, note = select_pair(pairs[key])
        rate, atten = key
        if chosen is None:
            print(f"WARNING: Fs={rate} atten={atten}: {note} - SKIPPING, no entry generated", file=sys.stderr)
            continue
        print(f"Fs={rate:.6g} atten={atten:.6g} -> M={chosen['M']} taps={chosen['tapCount']} "
              f"R_peak={chosen['rPeakPercent']:.4f}% T01={chosen['settlingMs']:.4f}ms  ({note})")
        entries.append((rate, atten, chosen))

    print(f"\n{len(entries)} entries selected out of {len(pairs)} pairs")

    with open(OUT_HEADER, "w") as f:
        f.write("#pragma once\n\n")
        f.write("// Auto-generated by SourceDetachedPole/PresetSweep/generate_bank_header.py\n")
        f.write("// from bank_sweep.csv. Do not hand-edit - regenerate from the sweep if the\n")
        f.write("// design method, cutoff, stopband target, or selection rule changes.\n")
        f.write("//\n")
        f.write("// Every entry is a precomputed bbk::parametric::designParametricFIR() result\n")
        f.write("// at a fixed cutoff (18500 Hz), stopband target (95 dB), and sidelobe decay\n")
        f.write("// (1.0, flat/undecayed) - only sample rate and attenuation-at-cutoff vary.\n")
        f.write("// This is the plugin's \"Default\" mode: an instant lookup instead of a live\n")
        f.write("// multi-second LP search, for the specific operating point found (by ear) to\n")
        f.write("// work well across the board. Taps are stored at their natural (unpadded)\n")
        f.write("// length - callers pad to the plugin's own fixed maxTapCount the same way a\n")
        f.write("// live Custom-mode design's taps are padded (see padTapsToFixedLength in\n")
        f.write("// DetachedPoleFilter.h), so Default and Custom modes share one latency\n")
        f.write("// contract.\n")
        f.write("\n#include <vector>\n\n")
        f.write("namespace bbk::detachedpole::presetbank\n{\n\n")
        f.write("constexpr double presetCutoffHz = 18500.0;\n")
        f.write("constexpr double presetStopbandRejectionDb = 95.0;\n")
        f.write("constexpr double presetSidelobeDecayRatio = 1.0;\n\n")
        f.write("struct BankEntry\n{\n")
        f.write("    double sampleRateHz;\n")
        f.write("    double attenuationAtCutoffDb;\n")
        f.write("    int tapCount;\n")
        f.write("    double rPeakPercent;\n")
        f.write("    double settlingMs;\n")
        f.write("    double achievedStopbandDb;\n")
        f.write("    std::vector<double> taps; // natural length == tapCount, unity DC gain\n")
        f.write("};\n\n")
        f.write(f"constexpr int numBankEntries = {len(entries)};\n\n")
        f.write("inline const std::vector<BankEntry>& bank()\n{\n")
        f.write("    static const std::vector<BankEntry> table = {\n")
        for rate, atten, chosen in entries:
            taps_str = ", ".join(fmt_double(t) for t in chosen["taps"])
            f.write(f"        {{ {fmt_double(rate)}, {fmt_double(atten)}, {chosen['tapCount']}, "
                    f"{fmt_double(chosen['rPeakPercent'])}, {fmt_double(chosen['settlingMs'])}, "
                    f"{fmt_double(chosen['worstStopbandDb'])},\n")
            f.write(f"          {{ {taps_str} }} }},\n")
        f.write("    };\n")
        f.write("    return table;\n")
        f.write("}\n\n")
        f.write("} // namespace bbk::detachedpole::presetbank\n")

    print(f"\nWrote {OUT_HEADER}")

if __name__ == "__main__":
    main()
