"""
Generate Source/TemporalFIRBank.h from fir_sweep_pareto_taps.json.

Every Pareto-set filter's native N-tap symmetric coefficient array is
zero-padded, centred, to a fixed length of MAX_N = 127 samples. Padding a
symmetric FIR with equal zeros on both sides does not change its frequency
response at all - it only formally reports the same impulse response at a
longer nominal length, which shifts its centre (and therefore its group
delay) out to (MAX_N-1)/2 = 63 samples. This is mathematically identical to
running the native filter and then adding (63 - nativeGroupDelay) samples
of pure extra delay, but it lets every entry in the bank share one common
127-tap convolution loop and one shared circular history buffer, with no
special-casing - the simplest correct way to guarantee every selectable
filter (and bypass, delayed separately by the same 63 samples) shares
identical total plugin latency.
"""
import json

MAX_N = 127
MAX_GROUP_DELAY = (MAX_N - 1) // 2  # 63

with open("fir_sweep_pareto_taps.json") as f:
    pareto = json.load(f)

pareto.sort(key=lambda m: m["settling_us"])

lines = []
lines.append("#pragma once")
lines.append("")
lines.append("#include <array>")
lines.append("#include <cstddef>")
lines.append("")
lines.append("// Auto-generated by gen_cpp_header.py from fir_sweep_pareto_taps.json.")
lines.append("// Do not hand-edit - regenerate from the sweep if the design changes.")
lines.append("//")
lines.append("// Every entry's taps[] is zero-padded/centred to MAX_N samples so every")
lines.append("// selectable filter (and bypass) shares exactly the same group delay,")
lines.append("// MAX_GROUP_DELAY samples - see file header comment above for why this")
lines.append("// is equivalent to explicit per-filter extra delay lines.")
lines.append("namespace bbk::temporalfir")
lines.append("{")
lines.append(f"constexpr int sampleRateHz = 192000;")
lines.append(f"constexpr int maxN = {MAX_N};")
lines.append(f"constexpr int maxGroupDelaySamples = {MAX_GROUP_DELAY};")
lines.append(f"constexpr double maxGroupDelayMicroseconds = {MAX_GROUP_DELAY} * 1.0e6 / 192000.0;")
lines.append("")
lines.append("struct FilterPoint")
lines.append("{")
lines.append("    int trueTapCount;")
lines.append("    int trueGroupDelaySamples;")
lines.append("    double peakSidelobePercent;")
lines.append("    double totalRingingEnergyPercent;")
lines.append("    double settlingMicroseconds;   // one-sided, centre to last tap > 0.1% of peak")
lines.append("    double worstPassbandErrorDb;")
lines.append("    double worstStopbandLevelDb;")
lines.append("    std::array<double, maxN> taps;  // zero-padded/centred to maxN, unity DC gain")
lines.append("};")
lines.append("")
lines.append(f"constexpr int numFilterPoints = {len(pareto)};")
lines.append("")
lines.append("inline const std::array<FilterPoint, numFilterPoints>& filterBank()")
lines.append("{")
lines.append("    static const std::array<FilterPoint, numFilterPoints> bank = { {")

for m in pareto:
    N = m["N"]
    taps = m["taps"]
    pad_total = MAX_N - N
    pad_left = pad_total // 2
    padded = [0.0] * pad_left + taps + [0.0] * (pad_total - pad_left)
    assert len(padded) == MAX_N

    taps_str = ", ".join(f"{v!r}" for v in padded)
    lines.append("        FilterPoint{")
    lines.append(f"            {N}, {m['group_delay_samples']},")
    lines.append(f"            {m['peak_sidelobe_pct']!r}, {m['total_ringing_energy_pct']!r},")
    lines.append(f"            {m['settling_us']!r}, {m['worst_passband_error_db']!r}, {m['worst_stopband_level_db']!r},")
    lines.append(f"            std::array<double, maxN>{{ {taps_str} }}")
    lines.append("        },")

lines.append("    } };")
lines.append("    return bank;")
lines.append("}")
lines.append("}")
lines.append("")

with open("TemporalFIRBank.h", "w") as f:
    f.write("\n".join(lines))

print(f"wrote TemporalFIRBank.h with {len(pareto)} filter points, {sum(1 for _ in open('TemporalFIRBank.h'))} lines")
